In [1]:
import pandas as pd
import numpy as np
from data import * 
from expenses import * 
from revenues import * 
from other import *
from model import *


from enum import Enum

ic| vals: array([56853000., 25000000.,  8150000.])


In [ ]:
a = np.array([56853000., 25000000.,  8150000.])
a/12

array([4737750.        , 2083333.33333333,  679166.66666667])

### Inputs 

In [ ]:
# revenues 
ppa_df

July 2026 - Year 1  July 2027 - Year 2  July 2028 - Year 3  \
Jan             6596040.0           6925842.0           7272134.1   
Feb             6596040.0           6925842.0           7272134.1   
Mar             6596040.0           6925842.0           7272134.1   
Apr             6596040.0           6925842.0           7272134.1   
May             6596040.0           6925842.0           7272134.1   
Jun             6943200.0           7290360.0           7654878.0   
Jul             6943200.0           7290360.0           7654878.0   
Aug             6943200.0           7290360.0           7654878.0   
Sep             6943200.0           7290360.0           7654878.0   
Oct             6596040.0           6925842.0           7272134.1   
Nov             6596040.0           6925842.0           7272134.1   
Dec             6596040.0           6925842.0           7272134.1   
Total          80541120.0          84568176.0          88796584.8   

       July 2029 - Year 4  July 2030 - Year 5  July 2031 - Year 6  \
Jan          7.635741e+06        8.017528e+06        8.418404e+06   
Feb          7.635741e+06        8.017528e+06        8.418404e+06   
Mar          7.635741e+06        8.017528e+06        8.418404e+06   
Apr          7.635741e+06        8.017528e+06        8.418404e+06   
May          7.635741e+06        8.017528e+06        8.418404e+06   
Jun          8.037622e+06        8.439503e+06        8.861478e+06   
Jul          8.037622e+06        8.439503e+06        8.861478e+06   
Aug          8.037622e+06        8.439503e+06        8.861478e+06   
Sep          8.037622e+06        8.439503e+06        8.861478e+06   
Oct          7.635741e+06        8.017528e+06        8.418404e+06   
Nov          7.635741e+06        8.017528e+06        8.418404e+06   
Dec          7.635741e+06        8.017528e+06        8.418404e+06   
Total        9.323641e+07        9.789823e+07        1.027931e+08   

       July 2032 - Year 7  July 2033 - Year 8  July 2034 - Year 9  \
Jan          8.839324e+06        9.281291e+06        9.745355e+06   
Feb          8.839324e+06        9.281291e+06        9.745355e+06   
Mar          8.839324e+06        9.281291e+06        9.745355e+06   
Apr          8.839324e+06        9.281291e+06        9.745355e+06   
May          8.839324e+06        9.281291e+06        9.745355e+06   
Jun          9.304552e+06        9.769780e+06        1.025827e+07   
Jul          9.304552e+06        9.769780e+06        1.025827e+07   
Aug          9.304552e+06        9.769780e+06        1.025827e+07   
Sep          9.304552e+06        9.769780e+06        1.025827e+07   
Oct          8.839324e+06        9.281291e+06        9.745355e+06   
Nov          8.839324e+06        9.281291e+06        9.745355e+06   
Dec          8.839324e+06        9.281291e+06        9.745355e+06   
Total        1.079328e+08        1.133294e+08        1.189959e+08   

       July 2035 - Year 10  ...  July 2056 - Year 31  July 2057 - Year 32  \
Jan           1.023262e+07  ...         2.850770e+07         2.993309e+07   
Feb           1.023262e+07  ...         2.850770e+07         2.993309e+07   
Mar           1.023262e+07  ...         2.850770e+07         2.993309e+07   
Apr           1.023262e+07  ...         2.850770e+07         2.993309e+07   
May           1.023262e+07  ...         2.850770e+07         2.993309e+07   
Jun           1.077118e+07  ...         3.000811e+07         3.150852e+07   
Jul           1.077118e+07  ...         3.000811e+07         3.150852e+07   
Aug           1.077118e+07  ...         3.000811e+07         3.150852e+07   
Sep           1.077118e+07  ...         3.000811e+07         3.150852e+07   
Oct           1.023262e+07  ...         2.850770e+07         2.993309e+07   
Nov           1.023262e+07  ...         2.850770e+07         2.993309e+07   
Dec           1.023262e+07  ...         2.850770e+07         2.993309e+07   
Total         1.249457e+08  ...         3.480941e+08         3.654988e+08   

       July 2058 - Year 33 

In [ ]:
# expenses 
exp_df

Financial Close - July 2023  Construction Year 1 - July 2024  \
Construction                  104646000.0                      317503000.0   
Operating                             0.0                              0.0   
Corporate                             0.0                        9602000.0   
Total                         104646000.0                      327105000.0   

              Commisioning and Construction Year 2 - July 2025  \
Construction                                       317503000.0   
Operating                                            9700000.0   
Corporate                                            9842050.0   
Total                                              337045050.0   

              July 2026 - Year 1  July 2027 - Year 2  July 2028 - Year 3  \
Construction                0.00        0.000000e+00        0.000000e+00   
Operating             3000000.00        3.000000e+06        3.000000e+06   
Corporate            10088101.25        1.034030e+07        1.059881e+07   
Total                13088101.25        1.334030e+07        1.359881e+07   

              July 2029 - Year 4  July 2030 - Year 5  July 2031 - Year 6  \
Construction        0.000000e+00        0.000000e+00        0.000000e+00   
Operating           3.000000e+06        3.000000e+06        3.000000e+06   
Corporate           1.086378e+07        1.113538e+07        1.141376e+07   
Total               1.386378e+07        1.413538e+07        1.441376e+07   

              July 2032 - Year 7  ...  July 2056 - Year 31  \
Construction        0.000000e+00  ...         0.000000e+00   
Operating           3.000000e+06  ...         3.110000e+06   
Corporate           1.169910e+07  ...         2.116047e+07   
Total               1.469910e+07  ...         2.427047e+07   

              July 2057 - Year 32  July 2058 - Year 33  July 2059 - Year 34  \
Construction         0.000000e+00         0.000000e+00         0.000000e+00   
Operating            3.110000e+06         3.110000e+06         3.110000e+06   
Corporate            2.168949e+07         2.223172e+07         2.278752e+07   
Total                2.479949e+07         2.534172e+07         2.589752e+07   

              July 2060 - Year 35  July 2061 - Year 36  July 2062 - Year 37  \
Construction         0.000000e+00         0.000000e+00         0.000000e+00   
Operating            3.110000e+06         3.110000e+06         3.110000e+06   
Corporate            2.335720e+07         2.394113e+07         2.453966e+07   
Total                2.646720e+07         2.705113e+07         2.764966e+07   

              July 2063 - Year 38  July 2064 - Year 39  July 2065 - Year 40  
Construction         0.000000e+00         0.000000e+00         0.000000e+00  
Operating            3.110000e+06         3.110000e+06         3.110000e+06  
Corporate            2.515315e+07         2.578198e+07         2.642653e+07  
Total                2.826315e+07         2.889198e+07         2.953653e+07  

[4 rows x 43 columns]

In [ ]:
debt_service_df

Financial Close - July 2023  \
Interest Payment                             0   
Prinicpal Payment                            0   
Fees                                         0   

                   Construction Year 1 - July 2024  \
Interest Payment                                 0   
Prinicpal Payment                                0   
Fees                                             0   

                   Commisioning and Construction Year 2 - July 2025  \
Interest Payment                                         16500000.0   
Prinicpal Payment                                               0.0   
Fees                                                       300000.0   

                   July 2026 - Year 1  July 2027 - Year 2  July 2028 - Year 3  \
Interest Payment           38122500.0          31766250.0          36110000.0   
Prinicpal Payment          11500000.0          13594494.0          14544335.0   
Fees                         635435.0            635435.0            635435.0   

                   July 2029 - Year 4  July 2030 - Year 5  July 2031 - Year 6  \
Interest Payment           29894750.0          33982500.0          27914900.0   
Prinicpal Payment          15906984.0          16823430.0          18940697.0   
Fees                         635435.0            589436.0            589436.0   

                   July 2032 - Year 7  ...  July 2056 - Year 31  \
Interest Payment           31303000.0  ...                    0   
Prinicpal Payment          19040508.0  ...                    0   
Fees                         589436.0  ...                    0   

                   July 2057 - Year 32  July 2058 - Year 33  \
Interest Payment                     0                    0   
Prinicpal Payment                    0                    0   
Fees                                 0                    0   

                   July 2059 - Year 34  July 2060 - Year 35  \
Interest Payment                     0                    0   
Prinicpal Payment                    0                    0   
Fees                                 0                    0   

                   July 2061 - Year 36  July 2062 - Year 37  \
Interest Payment                     0                    0   
Prinicpal Payment                    0                    0   
Fees                                 0                    0   

                   July 2063 - Year 38  July 2064 - Year 39  \
Interest Payment                     0                    0   
Prinicpal Payment                    0                    0   
Fees                                 0                    0   

                   July 2065 - Year 40  
Interest Payment                     0  
Prinicpal Payment                    0  
Fees                                 0  

[3 rows x 43 columns]

In [ ]:
# depreciation 
dep_df

Financial Close - July 2023  Construction Year 1 - July 2024  \
Depreciation                   35500000.0                       35500000.0   

              Commisioning and Construction Year 2 - July 2025  \
Depreciation                                        35500000.0   

              July 2026 - Year 1  July 2027 - Year 2  July 2028 - Year 3  \
Depreciation          35500000.0          35500000.0          35500000.0   

              July 2029 - Year 4  July 2030 - Year 5  July 2031 - Year 6  \
Depreciation          35500000.0          35500000.0          35500000.0   

              July 2032 - Year 7  July 2033 - Year 8  July 2034 - Year 9  \
Depreciation          35500000.0          35500000.0          35500000.0   

              July 2035 - Year 10  July 2036 - Year 11  July 2037 - Year 12  \
Depreciation           35500000.0           35500000.0           35500000.0   

              July 2038 - Year 13  July 2039 - Year 14  July 2040 - Year 15  \
Depreciation           35500000.0           35500000.0           35500000.0   

              July 2041 - Year 16  July 2042 - Year 17  
Depreciation           35500000.0           35500000.0

# calculation 

In [ ]:
### base case

In [ ]:
# base case
_, _, roe, _ = run_model(ppa_df, exp_df, debt_service_df, dep_df)
roe

24.890409338211366

### exchange rate fluctiations affecting EPC contract price 

In [ ]:
# TODO add to inputs! 
# price has fluctuated from 0.95 to 1.39 over past 10 years 
# https://www.xe.com/currencycharts/?from=EUR&to=USD&view=10Y
# lets do the full range, and then some, +/- 0.15
current_exchange = 1.30 # currently = 1.30 eur => us 

In [ ]:
currs = np.arange(0.80, 1.55, 0.05)
currs

array([0.8 , 0.85, 0.9 , 0.95, 1.  , 1.05, 1.1 , 1.15, 1.2 , 1.25, 1.3 ,
       1.35, 1.4 , 1.45, 1.5 ])

In [ ]:
(1.3-0.8)/0.01

50.0

In [ ]:
1670e3 - 1670000

0.0

In [ ]:
# 0.01 increase in exchange rate => EPC contract price increases / decreases by 1,670,000
epc_fluct = 1670e3/0.01

devs = (currs - current_exchange)*(epc_fluct)
devs


array([-8.3500000e+07, -7.5150000e+07, -6.6800000e+07, -5.8450000e+07,
       -5.0100000e+07, -4.1750000e+07, -3.3400000e+07, -2.5050000e+07,
       -1.6700000e+07, -8.3500000e+06,  7.4162898e-08,  8.3500000e+06,
        1.6700000e+07,  2.5050000e+07,  3.3400000e+07])

In [ ]:
def eval_epc_fluct(value):
    
    const_df_base = calc_epc_expenses(const_df, const_inputs, new_val=value)
    const_exp = make_const_exp(const_df_base) # return const_exp
    
    exp_df = calc_exp_df(const_exp, op_exp, corp_exp)

    _, _, roe, _ = run_model(ppa_df, exp_df, debt_service_df, dep_df)

    print(roe)

    return roe

eval_epc_fluct(0)

NameError: name 'calc_const_phase' is not defined

In [ ]:
epc_data["EPC Cost"][0]

455000000.0